spring:
  application:
    name: SmartAgriConnect

  datasource:
    url: jdbc:postgresql://localhost:5433/smartagri
    username: postgres
    password: bodif
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  jwt:
    secret: 6c067abf-a417-4007-a5c9-801392a21462